In [26]:
import pandas as pd
import numpy as np

In [27]:
# Create a dictionary to hold the data
data = {
    'Lesson': ['English Language 2', 'Physics 2', 'Discrete Mathematics', 'Electric and Electronic Circuits', 'Database Design'],
    'Semester_Passed': ['Even', 'Odd', 'Even', 'Even', 'Odd'],
    'ECTS': [2, 3, 3, 3, 3],
    'Specialized_or_General_or_Basic': ['General', 'General', 'Basic', 'Specialized', 'Specialized'],
    'Instructor': ['Hajari', 'Salimi', 'Ahmadi', 'Mohammadi', 'Bidki'],
    'Total_ECTS_in_Semester': [14, 17, 20, 14, 20],
    'Days_for_Final_Test': [2, 1, 1, 2, 0],
    'Nth_Test_of_Semester': [3, 2, 3, 3, 1],
    'Homework': ['Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
    'Quiz': ['No', 'Yes', 'Yes', 'Yes', 'Yes'],
    'Passed': ['Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
    'Conditionally_Passed': ['No', 'No', 'No', 'No', 'No'],
    'Grade': ['A', 'A', 'A', 'A', 'B']
}

In [28]:
df = pd.DataFrame(data)
print(df)

                             Lesson Semester_Passed  ECTS  \
0                English Language 2            Even     2   
1                         Physics 2             Odd     3   
2              Discrete Mathematics            Even     3   
3  Electric and Electronic Circuits            Even     3   
4                   Database Design             Odd     3   

  Specialized_or_General_or_Basic Instructor  Total_ECTS_in_Semester  \
0                         General     Hajari                      14   
1                         General     Salimi                      17   
2                           Basic     Ahmadi                      20   
3                     Specialized  Mohammadi                      14   
4                     Specialized      Bidki                      20   

   Days_for_Final_Test  Nth_Test_of_Semester Homework Quiz Passed  \
0                    2                     3      Yes   No    Yes   
1                    1                     2      Yes  Yes    

## 1)
1. Semester_Passed: Binary
2. ECTS: Numeric
3. Specialized_or_General_or_Basic: Ordianal
4. Instructor: Nominal
5. Total_ECTS_in_Semester: Numeric
6. Days_for_Final_Test: Numeric 
7. Nth_Test_of_Semester: Numeric 
8. Homework: Binary
9. Quiz: Binary
10. Passed: Binary
11. Conditionally_Passed: Binary
12. Grade: Ordinal

## 2)
1. Semester Passed: Low weight
2. ECTS: High weight
3. Specialized or General or Basic: Medium weight
4. Instructor: High weight
5. Total ECTS in Semester: High weight
6. Days for Final Test: Medium weight
7. Nth Test of Semester: Low weight
8. Homework: Medium weight
9. Quiz: Low weight
10. Passed: High weight
11. Conditionally Passed: Medium weight
12. Grade: High weight

## 3)

In [29]:

# Convert data to numpy array
num_data = len(data['Lesson'])
numeric_data = np.zeros((num_data, 5))  # 5 numeric attributes
numeric_data[:, 0] = data['ECTS']
numeric_data[:, 1] = data['Total_ECTS_in_Semester']
numeric_data[:, 2] = data['Days_for_Final_Test']
numeric_data[:, 3] = data['Nth_Test_of_Semester']

# Convert categorical data to numeric
instructor_mapping = {instructor: idx for idx, instructor in enumerate(set(data['Instructor']))}
semester_mapping = {'Odd': 0, 'Even': 1}
specialized_mapping = {'General': 0, 'Specialized': 2, 'Basic' : 1}
for i, lesson in enumerate(data['Lesson']):
    numeric_data[i, 4] = instructor_mapping[data['Instructor'][i]]

# Calculate distance matrix for each numeric attribute
dist_matrices = {}
for i in range(5):  
    dist_matrix = np.zeros((num_data, num_data))
    for row in range(num_data):
        for col in range(row):
            dist_matrix[row, col] = np.sqrt(np.sum((numeric_data[row, i] - numeric_data[col, i]) ** 2))
    dist_matrices[i] = dist_matrix

# Print distance matrix for each attribute
for key, matrix in dist_matrices.items():
    print(f"Distance Matrix for Attribute {key+1}:")
    print(matrix)
    print()

Distance Matrix for Attribute 1:
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]

Distance Matrix for Attribute 2:
[[0. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0.]
 [6. 3. 0. 0. 0.]
 [0. 3. 6. 0. 0.]
 [6. 3. 0. 6. 0.]]

Distance Matrix for Attribute 3:
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [2. 1. 1. 2. 0.]]

Distance Matrix for Attribute 4:
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [2. 1. 2. 2. 0.]]

Distance Matrix for Attribute 5:
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 2. 0. 0. 0.]
 [2. 3. 1. 0. 0.]
 [2. 1. 3. 4. 0.]]



In [31]:
print(df)

                             Lesson Semester_Passed  ECTS  \
0                English Language 2            Even     2   
1                         Physics 2             Odd     3   
2              Discrete Mathematics            Even     3   
3  Electric and Electronic Circuits            Even     3   
4                   Database Design             Odd     3   

  Specialized_or_General_or_Basic Instructor  Total_ECTS_in_Semester  \
0                         General     Hajari                      14   
1                         General     Salimi                      17   
2                           Basic     Ahmadi                      20   
3                     Specialized  Mohammadi                      14   
4                     Specialized      Bidki                      20   

   Days_for_Final_Test  Nth_Test_of_Semester Homework Quiz Passed  \
0                    2                     3      Yes   No    Yes   
1                    1                     2      Yes  Yes    

## 4)

In [30]:

weights = np.array([0.1, 0.5, 0.3, 0.5, 0.5, 0.3, 0.1, 0.3, 0.1, 0.5, 0.3, 0.5]) 

# Calculate weighted distance matrix for each attribute
weighted_dist_matrices = {}
for key, matrix in dist_matrices.items():
    weighted_dist_matrices[key] = matrix * weights[key]

# Print total weighted distance matrix for each attribute
for key, matrix in weighted_dist_matrices.items():
    print(f"Total Weighted Distance Matrix for Attribute {key+1}:")
    print(matrix)
    print()


Total Weighted Distance Matrix for Attribute 1:
[[0.  0.  0.  0.  0. ]
 [0.1 0.  0.  0.  0. ]
 [0.1 0.  0.  0.  0. ]
 [0.1 0.  0.  0.  0. ]
 [0.1 0.  0.  0.  0. ]]

Total Weighted Distance Matrix for Attribute 2:
[[0.  0.  0.  0.  0. ]
 [1.5 0.  0.  0.  0. ]
 [3.  1.5 0.  0.  0. ]
 [0.  1.5 3.  0.  0. ]
 [3.  1.5 0.  3.  0. ]]

Total Weighted Distance Matrix for Attribute 3:
[[0.  0.  0.  0.  0. ]
 [0.3 0.  0.  0.  0. ]
 [0.3 0.  0.  0.  0. ]
 [0.  0.3 0.3 0.  0. ]
 [0.6 0.3 0.3 0.6 0. ]]

Total Weighted Distance Matrix for Attribute 4:
[[0.  0.  0.  0.  0. ]
 [0.5 0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]
 [1.  0.5 1.  1.  0. ]]

Total Weighted Distance Matrix for Attribute 5:
[[0.  0.  0.  0.  0. ]
 [0.5 0.  0.  0.  0. ]
 [0.5 1.  0.  0.  0. ]
 [1.  1.5 0.5 0.  0. ]
 [1.  0.5 1.5 2.  0. ]]



## 5)
نرمال سازی : Min-Max Normalization

محاسبه فاصله بین داده ها : Euclidean Distance